"""Cypher script exporter for Neo4j direct import."""

import json
import math
import re
from pathlib import Path
from typing import Any, Literal, Mapping, TextIO, cast

import networkx as nx

from ..converters.config import ExportConfig

CypherStyle = Literal["merge", "create"]

# Identifiers that can appear unquoted in Cypher; anything else is backtick-quoted.
_PLAIN_IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


class CypherExporter:
    """Export graph to a cypher-shell ready script for Neo4j.

    Every statement is self-contained and ``;``-terminated, so the script can
    be piped through ``cypher-shell`` or executed statement-by-statement with
    the Neo4j driver. Property values keep their types: numbers, booleans and
    homogeneous scalar lists become Cypher literals; dicts (e.g. provenance)
    become JSON strings; anything else is stringified and escaped.

    Nodes are keyed on their canonical ``id`` attribute (falling back to the
    graph node key), which docling-graph guarantees unique per node. A
    uniqueness constraint per label is emitted at the top of the script so
    node lookups are index-backed instead of label scans.

    Styles:
        ``merge`` (default): idempotent. Nodes and relationships are MERGEd on
            identity only, with mutable properties applied via SET — loading
            into an empty database and re-loading produce the same graph.
        ``create``: plain CREATE statements. Faster on a first load but not
            re-runnable: a second run trips the uniqueness constraints instead
            of silently duplicating the graph.
    """

    def __init__(self, config: ExportConfig | None = None, style: CypherStyle = "merge") -> None:
        """Initialize Cypher exporter.

        Args:
            config: Export configuration. Uses defaults if None.
            style: Script style, ``merge`` (idempotent, default) or ``create``.

        Raises:
            ValueError: If style is not ``merge`` or ``create``.
        """
        if style not in ("merge", "create"):
            raise ValueError(f"Unknown Cypher style: {style!r} (expected 'merge' or 'create')")
        self.config = config or ExportConfig()
        self.style: CypherStyle = style

    def export(self, graph: nx.DiGraph, output_path: Path) -> None:
        """Export graph to Cypher script.

        Args:
            graph: NetworkX directed graph to export.
            output_path: File path where to save Cypher script.

        Raises:
            ValueError: If graph is empty.
        """
        if not self.validate_graph(graph):
            raise ValueError("Cannot export empty graph")

        output_path.parent.mkdir(parents=True, exist_ok=True)

        # (label, id literal) per node key — shared by node statements and the
        # relationship MATCHes so both sides always address the same node.
        identities = {
            node_id: (str(data.get("label") or "Node"), self._identity_literal(node_id, data))
            for node_id, data in graph.nodes(data=True)
        }

        with open(output_path, "w", encoding=self.config.CYPHER_ENCODING) as f:
            f.write("// Cypher script generated by docling-graph\n")
            if self.style == "merge":
                f.write("// Idempotent: safe to re-run (nodes MERGEd on their id).\n")
            else:
                f.write("// CREATE-style script: load into an empty database only.\n")
            f.write("// Load with: cypher-shell -f <this file>\n\n")

            f.write("// --- Constraints ---\n")
            for statement in self._constraint_statements(identities):
                f.write(statement)

            f.write("\n// --- Nodes ---\n")
            self._write_nodes(graph, identities, f)

            f.write("\n// --- Relationships ---\n")
            self._write_relationships(graph, identities, f)

    def validate_graph(self, graph: nx.DiGraph) -> bool:
        """Validate that graph is not empty.

        Args:
            graph: NetworkX directed graph.

        Returns:
            True if graph has nodes.
        """
        # number_of_nodes() is not typed in stubs; cast to int for mypy
        num_nodes = cast(int, graph.number_of_nodes())
        return num_nodes > 0

    @staticmethod
    def _escape_cypher_string(value: Any) -> str:
        """Escape strings for use in Cypher queries.

        Args:
            value: Value to escape.

        Returns:
            Escaped string safe for Cypher.
        """
        # Ensure we operate on a string for proper typing
        val_str: str = value if isinstance(value, str) else str(value)

        # Escape backslashes, quotes, and newlines
        return (
            val_str.replace("\\", "\\\\")
            .replace("'", "\\'")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
        )

    @staticmethod
    def _sanitize_identifier(identifier: str) -> str:
        """Sanitize identifier for use in Cypher.

        Args:
            identifier: Identifier to sanitize.

        Returns:
            Sanitized identifier safe for Cypher.
        """
        # Replace non-alphanumeric characters with underscore
        sanitized = re.sub(r"[^a-zA-Z0-9_]", "_", str(identifier))
        # Ensure it doesn't start with a number
        if sanitized and sanitized[0].isdigit():
            sanitized = "n_" + sanitized
        return sanitized or "node"

    @staticmethod
    def _format_identifier(name: str) -> str:
        """Label or property key, backtick-quoted unless it is a plain identifier."""
        if _PLAIN_IDENTIFIER.fullmatch(name):
            return name
        return "`" + name.replace("`", "``") + "`"

    def _quoted(self, value: str) -> str:
        return f'"{self._escape_cypher_string(value)}"'

    def _format_value(self, value: Any) -> str:
        """Cypher literal preserving the value's type.

        bool/int/float become Cypher literals (non-finite floats have no
        Cypher literal and fall back to quoted strings), lists become Cypher
        lists when Neo4j can store them (see ``_format_list``), dicts become
        JSON strings, and anything else is stringified and escaped.
        """
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, int):
            return str(value)
        if isinstance(value, float):
            return repr(value) if math.isfinite(value) else self._quoted(str(value))
        if isinstance(value, str):
            return self._quoted(value)
        if isinstance(value, list | tuple):
            return self._format_list(list(value))
        if isinstance(value, dict):
            return self._quoted(json.dumps(value, ensure_ascii=False, default=str))
        return self._quoted(str(value))

    @staticmethod
    def _scalar_kind(value: Any) -> str:
        if isinstance(value, bool):
            return "bool"
        if isinstance(value, int):
            return "int"
        if isinstance(value, float):
            return "float"
        if isinstance(value, str):
            return "str"
        return "other"

    def _format_list(self, values: list[Any]) -> str:
        """Cypher list literal for homogeneous scalar lists; JSON string otherwise.

        Neo4j only stores homogeneous lists of primitives as properties, so a
        mixed int/float list is coerced to floats and every other mix (dicts,
        nested lists, str+number, non-finite floats) falls back to a JSON
        string, like dict values do.
        """
        if not values:
            return "[]"
        kinds = {self._scalar_kind(v) for v in values}
        storable = kinds in ({"bool"}, {"int"}, {"float"}, {"str"}, {"int", "float"})
        if storable and "float" in kinds:
            storable = all(math.isfinite(v) for v in values if isinstance(v, float))
        if not storable:
            return self._quoted(json.dumps(values, ensure_ascii=False, default=str))
        if kinds == {"int", "float"}:
            return "[" + ", ".join(repr(float(v)) for v in values) + "]"
        return "[" + ", ".join(self._format_value(v) for v in values) + "]"

    def _identity_literal(self, node_id: Any, data: Mapping[str, Any]) -> str:
        """Literal for the node's identity key: the ``id`` attribute docling-graph
        stamps on every node (canonical, unique), else the graph node key."""
        raw = data.get("id")
        if raw is None:
            raw = node_id
        if isinstance(raw, bool) or not isinstance(raw, str | int | float):
            raw = str(raw)
        return self._format_value(raw)

    def _cypher_properties(
        self, data: Mapping[str, Any], exclude: tuple[str, ...]
    ) -> list[tuple[str, str]]:
        """(formatted key, literal) pairs for every property worth exporting.

        ``exclude`` keys and None values are dropped.
        """
        return [
            (self._format_identifier(str(key)), self._format_value(value))
            for key, value in data.items()
            if key not in exclude and value is not None
        ]

    def _constraint_statements(self, identities: Mapping[Any, tuple[str, str]]) -> list[str]:
        """One id-uniqueness constraint per distinct label.

        The constraint makes each MERGE/MATCH an index lookup instead of a
        label scan; without it, loading N nodes degrades to O(N^2).
        """
        statements = []
        used_names: set[str] = set()
        for label in sorted({label for label, _ in identities.values()}):
            # Constraint names share one namespace: disambiguate labels that
            # sanitize to the same name so IF NOT EXISTS cannot silently skip.
            base = self._sanitize_identifier(label).lower() + "_id"
            name, suffix = base, 2
            while name in used_names:
                name, suffix = f"{base}_{suffix}", suffix + 1
            used_names.add(name)
            statements.append(
                f"CREATE CONSTRAINT {name} IF NOT EXISTS "
                f"FOR (n:{self._format_identifier(label)}) REQUIRE n.id IS UNIQUE;\n"
            )
        return statements

    def _write_nodes(
        self, graph: nx.DiGraph, identities: Mapping[Any, tuple[str, str]], file: TextIO
    ) -> None:
        """Write one self-contained statement per node.

        Args:
            graph: NetworkX directed graph.
            identities: (label, id literal) per node key.
            file: File object to write to.
        """
        for node_id, data in graph.nodes(data=True):
            label, id_literal = identities[node_id]
            label_fmt = self._format_identifier(label)
            props = self._cypher_properties(data, exclude=("label", "id"))

            if self.style == "create":
                props_str = ", ".join(f"{k}: {v}" for k, v in [("id", id_literal), *props])
                file.write(f"CREATE (:{label_fmt} {{{props_str}}});\n")
            elif props:
                # Only the identity key belongs in the MERGE pattern — a
                # mutable property there would fail to match after an update
                # and create a duplicate node instead.
                file.write(f"MERGE (n:{label_fmt} {{id: {id_literal}}})\n")
                file.write("SET " + ", ".join(f"n.{k} = {v}" for k, v in props) + ";\n")
            else:
                file.write(f"MERGE (n:{label_fmt} {{id: {id_literal}}});\n")

    def _write_relationships(
        self, graph: nx.DiGraph, identities: Mapping[Any, tuple[str, str]], file: TextIO
    ) -> None:
        """Write one self-contained statement per relationship.

        Args:
            graph: NetworkX directed graph.
            identities: (label, id literal) per node key.
            file: File object to write to.
        """
        for source, target, data in graph.edges(data=True):
            source_label, source_id = identities[source]
            target_label, target_id = identities[target]
            rel_type = self._sanitize_identifier(str(data.get("label") or "RELATED_TO").upper())
            props = self._cypher_properties(data, exclude=("label",))

            # Both endpoints are label + id filtered: index-backed lookups,
            # never a cartesian product.
            file.write(
                f"MATCH (a:{self._format_identifier(source_label)} {{id: {source_id}}}), "
                f"(b:{self._format_identifier(target_label)} {{id: {target_id}}})\n"
            )
            if self.style == "create":
                props_str = ", ".join(f"{k}: {v}" for k, v in props)
                rel = f"[:{rel_type} {{{props_str}}}]" if props else f"[:{rel_type}]"
                file.write(f"CREATE (a)-{rel}->(b);\n")
            elif props:
                file.write(f"MERGE (a)-[r:{rel_type}]->(b)\n")
                file.write("SET " + ", ".join(f"r.{k} = {v}" for k, v in props) + ";\n")
            else:
                file.write(f"MERGE (a)-[:{rel_type}]->(b);\n")
