"""
Invoice extraction template. Extracts a graph-ready structure from invoices and credit notes:
header metadata, the parties involved, the billed line items, and the catalog of items they
reference.

Key entities:
- Invoice (root): The invoice document, identified by the number printed in the header.
- Party: An organization or person involved in the document (seller or buyer).
- Item: A product or service billed, identified by its printed name.
- LineItem: One row of the billing table, identified by its printed row number.

Key relationships:
- LineItem --REFERENCES_ITEM--> Item (by reference)
- Invoice --ISSUED_BY--> Party
- Invoice --BILLED_TO--> Party
- Invoice --CONTAINS_ITEM--> Item
- Invoice --CONTAINS_LINE--> LineItem
- Invoice --HAS_TAX--> Tax

Generated by docling-graph template generation v0.1.0 from invoice1.pdf, invoice2.pdf on
2026-07-16. Spec: invoice.spec.yaml.
"""

import logging
import re
from datetime import date, datetime
from enum import Enum
from typing import Any, List, Optional, Type

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing_extensions import Self

logger = logging.getLogger(__name__)


# -----------------------------------------------------------------------------
# Docling Graph edge helper
# -----------------------------------------------------------------------------
def edge(
    label: str,
    default: Any = None,
    *,
    reference: bool = False,
    closed_catalog: bool = False,
    **kwargs: Any,
) -> Any:
    """
    Declare a field as a graph edge for Docling-Graph via json_schema_extra.

    ``reference=True`` marks an identity-ONLY link (graph_reference): the field
    carries id-only references to entities described in full elsewhere in the
    schema. In dense extraction these references are filled by the PARENT's own
    fill call (never discovered separately), which preserves per-parent
    membership lists and avoids phantom parents.

    ``closed_catalog=True`` (reference_closed_catalog) declares that the targets
    form a CLOSED catalog defined elsewhere in the document: a target that only
    exists through this field (never instantiated or referenced otherwise) is a
    hallucinated member — the converter then drops the edge (and the orphaned
    target), unless that would wipe more than half of the target class.
    """
    json_schema_extra = dict(kwargs.pop("json_schema_extra", {}) or {})
    json_schema_extra["edge_label"] = label
    if reference:
        json_schema_extra["graph_reference"] = True
    if closed_catalog:
        json_schema_extra["reference_closed_catalog"] = True

    if "default_factory" in kwargs:
        default_factory = kwargs.pop("default_factory")
        return Field(default_factory=default_factory, json_schema_extra=json_schema_extra, **kwargs)

    return Field(default, json_schema_extra=json_schema_extra, **kwargs)


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
def _normalize_enum(enum_cls: Type[Enum], v: Any) -> Any:
    """
    Accept enum instances, value strings, or member names.
    Handles various formats: 'VALUE', 'value', 'Value', 'VALUE_NAME'.
    Falls back to the OTHER member instead of rejecting (never raises).
    """
    if isinstance(v, enum_cls):
        return v
    if isinstance(v, str):
        key = re.sub(r"[^A-Za-z0-9]+", "", v).lower()
        mapping: dict[str, Any] = {}
        for member in enum_cls:
            mapping[re.sub(r"[^A-Za-z0-9]+", "", member.name).lower()] = member
            mapping[re.sub(r"[^A-Za-z0-9]+", "", str(member.value)).lower()] = member
        if key in mapping:
            return mapping[key]
    if "OTHER" in enum_cls.__members__:
        logger.warning("Unmapped enum value %r for %s; falling back to OTHER", v, enum_cls.__name__)
        return enum_cls.OTHER
    return v


# -----------------------------------------------------------------------------
# Enums
# -----------------------------------------------------------------------------
class DocumentType(str, Enum):
    """Controlled vocabulary for document_type values. Unmapped values normalize to OTHER."""

    INVOICE = "Invoice"
    CREDIT_NOTE = "Credit Note"
    RECEIPT = "Receipt"
    OTHER = "Other"


# -----------------------------------------------------------------------------
# Components
# -----------------------------------------------------------------------------
class Tax(BaseModel):
    """Tax bracket applied at document level. Deduplicated by content, never a standalone node."""

    model_config = ConfigDict(is_entity=False)

    tax_type: Optional[str] = Field(
        None,
        description="Type of tax as printed (VAT, GST, Sales Tax).",
        examples=["VAT", "GST"],
    )

    tax_amount: Optional[float] = Field(
        None,
        description="Tax amount for this bracket, numeric value only.",
        examples=["200.00", "1 500,00"],
    )

    @field_validator("tax_amount", mode="before")
    @classmethod
    def _coerce_tax_amount_numeric(cls, v: Any) -> Any:
        """Coerce numeric strings ('1 500,00', '$1,500.00') to float; never rejects."""
        if not isinstance(v, str):
            return v
        cleaned = re.sub(r"[^\d,.\-]", "", v)
        if "," in cleaned:
            if re.search(r",\d\d?$", cleaned):
                cleaned = cleaned.replace(".", "").replace(",", ".")
            else:
                cleaned = cleaned.replace(",", "")
        try:
            return float(cleaned)
        except ValueError:
            logger.warning("Could not parse numeric value %r; dropping it", v)
            return None

    def __str__(self) -> str:
        parts = [self.tax_type, self.tax_amount]
        return " ".join(str(p) for p in parts if p) or "Unknown"


# -----------------------------------------------------------------------------
# Entities
# -----------------------------------------------------------------------------
class Party(BaseModel):
    """
    An organization or person involved in the document (seller or buyer). NOT the item catalog.
    Identified by its printed name.
    """

    model_config = ConfigDict(graph_id_fields=["name"])

    name: str = Field(
        ...,
        description="Full legal name of the party as printed in the header.",
        examples=["Acme GmbH", "Beta SARL"],
    )

    tax_id: Optional[str] = Field(
        None,
        description="VAT number or tax identifier if printed near the name.",
        examples=["FR12345678901"],
    )

    def __str__(self) -> str:
        parts = [self.name, self.tax_id]
        return " ".join(str(p) for p in parts if p) or "Unknown"


class Item(BaseModel):
    """
    A product or service billed, identified by its printed name. NOT the billing row (see LineItem);
    the same Item can recur across several rows.
    """

    model_config = ConfigDict(graph_id_fields=["name"])

    name: str = Field(
        ...,
        description="Item name copied verbatim from the description column.",
        examples=["USB-C cable", "Dock DS-300"],
    )

    category: Optional[str] = Field(
        None,
        description="Item category or classification when stated.",
        examples=["Electronics"],
    )

    def __str__(self) -> str:
        parts = [self.name, self.category]
        return " ".join(str(p) for p in parts if p) or "Unknown"


class LineItem(BaseModel):
    """
    One row of the billing table, identified by its printed row number. NOT the product itself (see
    Item).
    """

    model_config = ConfigDict(graph_id_fields=["line_number"])

    line_number: str = Field(
        ...,
        description="Row number printed in the first column of the billing table.",
        examples=["1", "2"],
    )

    quantity: Optional[float] = Field(
        None,
        description="LOOK FOR the Qty column of the row, numeric value only.",
        examples=["2"],
    )

    item: Optional[Item] = edge(
        label="REFERENCES_ITEM",
        reference=True,
        closed_catalog=True,
        description=(
            "The catalog item billed on this row, referenced by name only; the full detail of "
            "every item lives once in Invoice.items."
        ),
    )

    @field_validator("quantity", mode="before")
    @classmethod
    def _coerce_quantity_numeric(cls, v: Any) -> Any:
        """Coerce numeric strings ('1 500,00', '$1,500.00') to float; never rejects."""
        if not isinstance(v, str):
            return v
        cleaned = re.sub(r"[^\d,.\-]", "", v)
        if "," in cleaned:
            if re.search(r",\d\d?$", cleaned):
                cleaned = cleaned.replace(".", "").replace(",", ".")
            else:
                cleaned = cleaned.replace(",", "")
        try:
            return float(cleaned)
        except ValueError:
            logger.warning("Could not parse numeric value %r; dropping it", v)
            return None

    def __str__(self) -> str:
        parts = [self.line_number, self.quantity]
        return " ".join(str(p) for p in parts if p) or "Unknown"


# -----------------------------------------------------------------------------
# Root document
# -----------------------------------------------------------------------------
class Invoice(BaseModel):
    """The invoice document, identified by the number printed in the header. One per document."""

    model_config = ConfigDict(graph_id_fields=["document_number"])

    document_number: str = Field(
        ...,
        description="Invoice number printed in the header, including prefixes.",
        examples=["INV-2024-0113", "2024-INV-12345"],
    )

    document_type: DocumentType = Field(
        DocumentType.OTHER,
        description=(
            "The document type printed as the title. Synonyms: map 'Facture' -> 'Invoice'; 'Bill' "
            "-> 'Invoice'; 'Avoir' -> 'Credit Note'."
        ),
        examples=["Invoice"],
    )

    issue_date: Optional[date] = Field(
        None,
        description="Issue date printed in the header, normalized to YYYY-MM-DD.",
        examples=["2024-01-15"],
    )

    currency: Optional[str] = Field(
        None,
        description="Document currency as an ISO 4217 code near the totals.",
        examples=["EUR", "USD"],
    )

    tags: List[str] = Field(
        default_factory=list,
        description="Free-form document tags printed near the footer, one per keyword.",
        examples=["priority"],
    )

    mentioned_document_types: List[DocumentType] = Field(
        default_factory=list,
        description=(
            "Types of other documents mentioned in the footer, one per mention. Synonyms: map "
            "'Facture' -> 'Invoice'; 'Bill' -> 'Invoice'; 'Avoir' -> 'Credit Note'."
        ),
        examples=["Receipt"],
    )

    seller: Optional[Party] = edge(
        label="ISSUED_BY",
        description="The party that issued the document (header, 'Seller' or 'From').",
    )

    buyer: Optional[Party] = edge(
        label="BILLED_TO",
        description="The party billed by the document ('Bill To' or 'Buyer').",
    )

    items: List[Item] = edge(
        label="CONTAINS_ITEM",
        default_factory=list,
        description=(
            "Catalog of all distinct items billed in the document — the canonical home of each "
            "Item's full detail, extracted once."
        ),
    )

    line_items: List[LineItem] = edge(
        label="CONTAINS_LINE",
        default_factory=list,
        description="Every row of the billing table, in printed order.",
    )

    taxes: List[Tax] = edge(
        label="HAS_TAX",
        default_factory=list,
        description="Document-level tax brackets from the totals section.",
    )

    @field_validator("document_type", mode="before")
    @classmethod
    def _normalize_document_type(cls, v: Any) -> Any:
        """Map free-text values onto DocumentType members (falls back to OTHER)."""
        return _normalize_enum(DocumentType, v)

    @field_validator("currency", mode="before")
    @classmethod
    def _normalize_currency_currency(cls, v: Any) -> Any:
        """Normalize currency symbols and casing to ISO 4217 codes; never rejects."""
        if not v:
            return v
        symbol_map = {
            "€": "EUR",
            "$": "USD",
            "£": "GBP",
            "¥": "JPY",
        }
        v_str = str(v).strip()
        if v_str in symbol_map:
            return symbol_map[v_str]
        v_upper = v_str.upper()
        if len(v_upper) == 3 and v_upper.isalpha():
            return v_upper
        logger.warning("Currency %r does not match ISO 4217 format; kept as %r", v, v_upper)
        return v_upper

    @field_validator("tags", mode="before")
    @classmethod
    def _coerce_tags_list(cls, v: Any) -> Any:
        """Ensure tags is always a list (accepts bare or comma-separated strings)."""
        if isinstance(v, str):
            if "," in v:
                return [part.strip() for part in v.split(",") if part.strip()]
            return [v]
        if v is None:
            return []
        return v

    @field_validator("mentioned_document_types", mode="before")
    @classmethod
    def _normalize_mentioned_document_types(cls, v: Any) -> Any:
        """Map free-text list items onto DocumentType members (falls back to OTHER)."""
        if isinstance(v, list):
            return [_normalize_enum(DocumentType, item) for item in v]
        return _normalize_enum(DocumentType, v)

    @model_validator(mode="after")
    def _deduplicate_tags(self) -> Self:
        """Keep first occurrence per key (removes duplicates from chunked extraction)."""
        if not self.tags:
            return self
        seen: set[str] = set()
        unique: list[Any] = []
        for item in self.tags:
            key = str(item).strip().lower()
            if key not in seen:
                seen.add(key)
                unique.append(item)
        object.__setattr__(self, "tags", unique)
        return self

    @model_validator(mode="after")
    def _deduplicate_taxes(self) -> Self:
        """Keep first occurrence per key (removes duplicates from chunked extraction)."""
        if not self.taxes:
            return self
        seen: set[str] = set()
        unique: list[Any] = []
        for item in self.taxes:
            key = str(getattr(item, "tax_type", "") or "").strip().lower()
            if key not in seen:
                seen.add(key)
                unique.append(item)
        object.__setattr__(self, "taxes", unique)
        return self

    @model_validator(mode="after")
    def _deduplicate_mentioned_document_types(self) -> Self:
        """Keep first occurrence per key (removes duplicates from chunked extraction)."""
        if not self.mentioned_document_types:
            return self
        seen: set[str] = set()
        unique: list[Any] = []
        for item in self.mentioned_document_types:
            key = str(item).strip().lower()
            if key not in seen:
                seen.add(key)
                unique.append(item)
        object.__setattr__(self, "mentioned_document_types", unique)
        return self

    def __str__(self) -> str:
        parts = [self.document_number, self.issue_date]
        return " ".join(str(p) for p in parts if p) or "Unknown"


# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------
# This template passed generation gates V1-V6 (parse, import allowlist,
# load, structured-output schema, dense catalog walk, graph-shape smoke
# test). Comments never reach extraction prompts — only class docstrings
# and field descriptions do. After hand edits, re-verify with:
#
#     docling-graph template lint <module.path.Invoice>
