"""
Organizational chart extraction template exercising recursive and mutually referential entities.

Key entities:
- OrgChart (root): The chart document root, identified by its printed title.
- Section: A numbered section of the chart document.
- Person: A person named in the chart.
- Organization: An organization in the chart.

Key relationships:
- Section --CONTAINS_SECTION--> Section (by reference)
- Person --EMPLOYED_BY--> Organization (by reference)
- Organization --EMPLOYS--> Person
- OrgChart --HAS_ORGANIZATION--> Organization
- OrgChart --CONTAINS_SECTION--> Section

Generated by docling-graph template generation.
"""

from typing import Any, List, Optional

from pydantic import BaseModel, ConfigDict, Field


# -----------------------------------------------------------------------------
# Docling Graph edge helper
# -----------------------------------------------------------------------------
def edge(
    label: str,
    default: Any = None,
    *,
    reference: bool = False,
    closed_catalog: bool = False,
    **kwargs: Any,
) -> Any:
    """
    Declare a field as a graph edge for Docling-Graph via json_schema_extra.

    ``reference=True`` marks an identity-ONLY link (graph_reference): the field
    carries id-only references to entities described in full elsewhere in the
    schema. In dense extraction these references are filled by the PARENT's own
    fill call (never discovered separately), which preserves per-parent
    membership lists and avoids phantom parents.

    ``closed_catalog=True`` (reference_closed_catalog) declares that the targets
    form a CLOSED catalog defined elsewhere in the document: a target that only
    exists through this field (never instantiated or referenced otherwise) is a
    hallucinated member — the converter then drops the edge (and the orphaned
    target), unless that would wipe more than half of the target class.
    """
    json_schema_extra = dict(kwargs.pop("json_schema_extra", {}) or {})
    json_schema_extra["edge_label"] = label
    if reference:
        json_schema_extra["graph_reference"] = True
    if closed_catalog:
        json_schema_extra["reference_closed_catalog"] = True

    if "default_factory" in kwargs:
        default_factory = kwargs.pop("default_factory")
        return Field(default_factory=default_factory, json_schema_extra=json_schema_extra, **kwargs)

    return Field(default, json_schema_extra=json_schema_extra, **kwargs)


# -----------------------------------------------------------------------------
# Entities
# -----------------------------------------------------------------------------
class Section(BaseModel):
    """A numbered section of the chart document. Sections nest recursively into subsections."""

    model_config = ConfigDict(graph_id_fields=["section_number"])

    section_number: str = Field(
        ...,
        description="Section number as printed in the heading.",
        examples=["1", "2.1"],
    )

    subsections: List["Section"] = edge(
        label="CONTAINS_SECTION",
        default_factory=list,
        reference=True,
        description="Nested subsections of this section, referenced by number only.",
    )

    def __str__(self) -> str:
        parts = [self.section_number]
        return " ".join(str(p) for p in parts if p) or "Unknown"


class Person(BaseModel):
    """A person named in the chart. NOT an organization."""

    model_config = ConfigDict(graph_id_fields=["full_name"])

    full_name: str = Field(
        ...,
        description="Full name as printed.",
        examples=["Ada Lovelace", "Grace Hopper"],
    )

    works_for: Optional["Organization"] = edge(
        label="EMPLOYED_BY",
        reference=True,
        description="The organization employing this person, referenced by name only.",
    )

    def __str__(self) -> str:
        parts = [self.full_name]
        return " ".join(str(p) for p in parts if p) or "Unknown"


class Organization(BaseModel):
    """An organization in the chart. NOT a person."""

    model_config = ConfigDict(graph_id_fields=["name"])

    name: str = Field(
        ...,
        description="Organization name as printed.",
        examples=["Acme Research"],
    )

    employees: List[Person] = edge(
        label="EMPLOYS",
        default_factory=list,
        description="People employed by this organization.",
    )

    def __str__(self) -> str:
        parts = [self.name]
        return " ".join(str(p) for p in parts if p) or "Unknown"


# -----------------------------------------------------------------------------
# Root document
# -----------------------------------------------------------------------------
class OrgChart(BaseModel):
    """The chart document root, identified by its printed title."""

    model_config = ConfigDict(graph_id_fields=["chart_title"])

    chart_title: str = Field(
        ...,
        description="Title printed on the first page.",
        examples=["Company Org Chart 2026"],
    )

    organizations: List[Organization] = edge(
        label="HAS_ORGANIZATION",
        default_factory=list,
        description="Organizations described by the chart.",
    )

    sections: List[Section] = edge(
        label="CONTAINS_SECTION",
        default_factory=list,
        description="Top-level sections of the chart document.",
    )

    def __str__(self) -> str:
        parts = [self.chart_title]
        return " ".join(str(p) for p in parts if p) or "Unknown"


Section.model_rebuild()
Person.model_rebuild()


# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------
# Graph-shape smoke test mirroring the templategen verification gate (V6).
# Re-run it by hand after editing this template:
#
#     from docling_graph.core.converters.graph_converter import GraphConverter
#
#     sample = OrgChart.model_validate(
#         {'chart_title': 'Company Org Chart 2026',
#          'organizations': [{'name': 'Acme Research',
#                             'employees': [{'full_name': 'Ada Lovelace'}]}],
#          'sections': [{'section_number': '1'}]}
#     )
#     graph, _metadata = GraphConverter().pydantic_list_to_graph([sample])
#     assert not graph.graph.get("empty_identity_nodes")
#     print(graph.number_of_nodes(), "nodes /", graph.number_of_edges(), "edges")
