"""
Insurance policy structure compiled deterministically from an OWL ontology.

Key entities:
- Policy (root): An insurance contract document.
- Guarantee: A named guarantee/coverage offered by the policy.

Key relationships:
- Policy --COVERS--> Guarantee

Generated by docling-graph template generation from policy.ttl.
"""

from datetime import date, datetime
from typing import Any, List, Optional

from pydantic import BaseModel, ConfigDict, Field


# -----------------------------------------------------------------------------
# Docling Graph edge helper
# -----------------------------------------------------------------------------
def edge(
    label: str,
    default: Any = None,
    *,
    reference: bool = False,
    closed_catalog: bool = False,
    **kwargs: Any,
) -> Any:
    """
    Declare a field as a graph edge for Docling-Graph via json_schema_extra.

    ``reference=True`` marks an identity-ONLY link (graph_reference): the field
    carries id-only references to entities described in full elsewhere in the
    schema. In dense extraction these references are filled by the PARENT's own
    fill call (never discovered separately), which preserves per-parent
    membership lists and avoids phantom parents.

    ``closed_catalog=True`` (reference_closed_catalog) declares that the targets
    form a CLOSED catalog defined elsewhere in the document: a target that only
    exists through this field (never instantiated or referenced otherwise) is a
    hallucinated member — the converter then drops the edge (and the orphaned
    target), unless that would wipe more than half of the target class.
    """
    json_schema_extra = dict(kwargs.pop("json_schema_extra", {}) or {})
    json_schema_extra["edge_label"] = label
    if reference:
        json_schema_extra["graph_reference"] = True
    if closed_catalog:
        json_schema_extra["reference_closed_catalog"] = True

    if "default_factory" in kwargs:
        default_factory = kwargs.pop("default_factory")
        return Field(default_factory=default_factory, json_schema_extra=json_schema_extra, **kwargs)

    return Field(default, json_schema_extra=json_schema_extra, **kwargs)


# -----------------------------------------------------------------------------
# Entities
# -----------------------------------------------------------------------------
class Guarantee(BaseModel):
    """
    A named guarantee/coverage offered by the policy. NOT an exclusion clause. At most 6 per
    document.
    """

    model_config = ConfigDict(graph_id_fields=["guarantee_name"], graph_max_instances=12)

    guarantee_name: str = Field(
        ...,
        description="Name of the guarantee as printed in the section heading.",
        examples=[],  # TODO(docling-graph): add 2-5 verbatim examples
    )

    description: Optional[str] = Field(
        None,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    def __str__(self) -> str:
        parts = [self.guarantee_name, self.description]
        return " ".join(str(p) for p in parts if p) or "Unknown"


# -----------------------------------------------------------------------------
# Root document
# -----------------------------------------------------------------------------
class Policy(BaseModel):
    """An insurance contract document."""

    model_config = ConfigDict(graph_id_fields=["policy_number"])

    policy_number: str = Field(
        ...,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
        examples=[],  # TODO(docling-graph): add 2-5 verbatim examples
    )

    effective_date: Optional[date] = Field(
        None,
        description="Date the policy takes effect.",
    )

    covers: List[Guarantee] = edge(
        label="COVERS",
        default_factory=list,
        description="Guarantees covered by this policy.",
    )

    def __str__(self) -> str:
        parts = [self.policy_number, self.effective_date]
        return " ".join(str(p) for p in parts if p) or "Unknown"


# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------
# Graph-shape smoke test mirroring the templategen verification gate (V6).
# Re-run it by hand after editing this template:
#
#     from docling_graph.core.converters.graph_converter import GraphConverter
#
#     sample = Policy.model_validate(
#         {'policy_number': 'sample-policy_number',
#          'covers': [{'guarantee_name': 'sample-guarantee_name'}]}
#     )
#     graph, _metadata = GraphConverter().pydantic_list_to_graph([sample])
#     assert not graph.graph.get("empty_identity_nodes")
#     print(graph.number_of_nodes(), "nodes /", graph.number_of_edges(), "edges")
